### ISSUE TITLE
提交N个bug

### ISSUE THREAD

**Issue by MGod-monkey** [dominoar/QCPNovelAi#1]
## 1，改一下README上的安装插件的指令，那个指令压根不对：
> !plugin + 仓库链接

![Snipaste_2023-02-11_23-55-37](https://user-images.githubusercontent.com/62071831/218267958-c621367b-9062-4406-8050-047963755b4a.png)

建议链接加个镜像链接选项，github的网速太慢了，类似https://kgithub.com/xxx， 我下插件都是用镜像网站

## 2，修改内部代码（直接导致无法运行）

you look look你仓库名跟main里面导入的模块是一个名吗？

![Snipaste_2023-02-11_21-43-08](https://user-images.githubusercontent.com/62071831/218268094-eaf9ffb1-941d-49d8-a028-2be6107b99a9.png)

估计这里偷懒了吧，我是直接图省事改目录名了

## 3，加个**requirements.txt**

运行插件一堆依赖没安上，正常运行了进入故事模式还报模块没安，醉了，不知道还有没有没安的
![Snipaste_2023-02-11_23-45-07](https://user-images.githubusercontent.com/62071831/218268354-a9fd7fa5-11d1-4933-9d21-ee36c1224f47.png)
![Snipaste_2023-02-11_23-51-26](https://user-images.githubusercontent.com/62071831/218268359-ca2e16c0-50f2-4ee3-bb3b-810af4b5d77b.png)

## 4，小建议

> QChatGPT在通过克隆仓库的时候好像不会修改**QChatGPT\plugins\switch.json**文件，后面还是我手动修改的，建议把这段代码补上

> 建议!story里面help能更详细一点，给不懂得怎么使用NovelAi的更快上手

## 最后，算了不用了（我是边弄插件边写的）

谷歌翻译库跟我其他库冲突了，安装新版本的httpcore，谷歌翻译库又不能用，安装旧的，其他的库又有问题，适配版本要改的代码量估计很大，算了，妥协了，反正一堆问题吧
![Snipaste_2023-02-12_00-30-38](https://user-images.githubusercontent.com/62071831/218269794-1b162405-f4c6-4c9f-8403-9a497b1ce8c0.png)
![Snipaste_2023-02-12_00-36-04](https://user-images.githubusercontent.com/62071831/218269796-bc128311-18cd-416e-a4ce-fc7238e27346.png)

**Comment by dildooblib** [comment]
问一下大佬no module named“yaml”怎么处理

**Comment by MGod-monkey** [comment]
看一下是不是没安装模块pip install pyyaml

**Comment by zhexiuamoy** [comment]
> 问一下大佬没有名为“yaml”的模块怎么处理

我也是这样 然后bot直接不能用了 搞得我重装了一个bot

**Comment by dominoar** [comment]
非常感谢你的反馈，你所描述的问题除谷歌翻译问题，均在v0.1.3中修复！

**Comment by dominoar** [comment]
请你重新使用!plugin 仓库地址进行更新

**Comment by dominoar** [comment]
非常感谢你的反馈，你所描述的问题除谷歌翻译问题，均在v0.1.3中修复！
